#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/lms.services/lms.services.coursemanagement/lms.services.coursemanagement.csproj", "src/lms.services/lms.services.coursemanagement/"]
COPY ["src/lms.buildingblocks/lms.buildingblocks.csproj", "src/lms.buildingblocks/"]
COPY ["src/lms.shared.common/lms.shared.common.csproj", "src/lms.shared.common/"]
COPY ["src/lms.shared.data/lms.shared.data.csproj", "src/lms.shared.data/"]
COPY ["src/lms.services.aws/lms.services.aws.csproj", "src/lms.services.aws/"]
RUN dotnet restore "src/lms.services/lms.services.coursemanagement/lms.services.coursemanagement.csproj"
COPY . .
WORKDIR "/src/src/lms.services/lms.services.coursemanagement"
RUN dotnet build "lms.services.coursemanagement.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "lms.services.coursemanagement.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "lms.services.coursemanagement.dll"]
