<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>46818e14-b8d2-48d7-8812-144a55a03ac1</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Refit" Version="9.0.2" />
    <PackageReference Include="Refit.HttpClientFactory" Version="9.0.2" />
    <PackageReference Include="Refit.Newtonsoft.Json" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\lms.buildingblocks\lms.buildingblocks.csproj" />
    <ProjectReference Include="..\lms.shared.common\lms.shared.common.csproj" />
  </ItemGroup>

</Project>
