<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fc2edd6b-c647-414a-96e6-5ee8ba0119ad</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UserManagement\V2\GetUserByEmail\**" />
    <Compile Remove="UserRetrieval\**" />
    <Content Remove="UserManagement\V2\GetUserByEmail\**" />
    <Content Remove="UserRetrieval\**" />
    <EmbeddedResource Remove="UserManagement\V2\GetUserByEmail\**" />
    <EmbeddedResource Remove="UserRetrieval\**" />
    <None Remove="UserManagement\V2\GetUserByEmail\**" />
    <None Remove="UserRetrieval\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="UserManagement\V1\CreateUser\CreateUserEndpoint.cs" />
    <Compile Remove="UserManagement\V1\CreateUser\CreateUserHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="Carter" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UserManagement\V1\CreateUser\" />
    <Folder Include="UserManagement\V2\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\aspire\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\lms.buildingblocks\lms.buildingblocks.csproj" />
    <ProjectReference Include="..\..\lms.shared.common\lms.shared.common.csproj" />
    <ProjectReference Include="..\..\lms.shared.data\lms.shared.data.csproj" />
  </ItemGroup>

</Project>
